# Generated by Django 3.0.6 on 2020-05-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-id']},
        ),
    ]
